version: '3.8'

services:
  nsp_backend:
    container_name: nsp_backend
    image: francescoxx/node-docker:0.0.4
    build:
      context: .
    ports:
      - '3001:3001'
    environment:
      - EXTERNAL_PORT=3001
      - PGUSER=francesco
      - PGPASSWORD=12345
      - PGDATABASE=nps_database
      - PGHOST=nsp_db # NAME OF THE SERVICE
    depends_on:
      - nsp_db
  nsp_db:
    container_name: nsp_db
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=nps_database
    volumes:
      - nps_data:/var/lib/postgresql/data
  grafana:
    container_name: grafana
    image: grafana/grafana:5.4.3
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - nsp_db
volumes:
  nps_data: {}
  grafana-storage: {}
