version: '3.8'

services:
  nsp_backend:
    container_name: nsp_backend
    image: francescoxx/social-data-dashboard:0.0.5
    build:
      context: .
    ports:
      - '3001:3001'
    environment:
      - EXTERNAL_PORT=3001
      - PGUSER=francesco
      - PGPASSWORD=12345
      - PGDATABASE=nps_database
      - PGHOST=nsp_db # NAME OF THE SERVICE
    depends_on:
      - nsp_db
    networks:
      - nsp_network
  nsp_db:
    container_name: nsp_db
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=nps_database
    networks:
      - nsp_network
    volumes:
      - nps_data:/var/lib/postgresql/data
  grafana:
    container_name: grafana
    image: grafana/grafana:5.4.3
    ports:
      - '3002:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - nsp_network
    depends_on:
      - nsp_db
  twitterclient:
    image: francescoxx/nodejs-twitter-api-server-example:1.0.1
    ports:
      - '3003:3003'
    environment:
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
    networks:
      - nsp_network
  pgadmin4:
    image: dpage/pgadmin4:4.30
    ports:
      - 7750:80
    networks:
      - nsp_network
    depends_on:
      - nsp_db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  nps_data: {}
  grafana-storage: {}
  pgadmin_data:

networks:
  nsp_network: {}
